26-03-2019 12:26:35 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:26:35 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:26:35 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:26:35 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:26:35 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:26:36 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:26:36 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:26:36 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:26:36 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:26:36 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:27:02 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19772) already exists.
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19772) already exists.
26-03-2019 12:27:12 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:27:15 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:18 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:18 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:18 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:18 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:27:18 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:19 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:19 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:19 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:19 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:27:19 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:39 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:39 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:39 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:39 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:27:39 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:40 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:40 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:40 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:40 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:27:40 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:27:56 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:28:02 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:28:02 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:28:02 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:28:02 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:28:02 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:28:03 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:28:03 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:28:03 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:28:03 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:28:03 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:28:43 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:28:43 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=81290, type_id=4, value='21111' where id=81293 was aborted.  Call getNextException to see the cause.
26-03-2019 12:28:43 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:28:43 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21111) already exists.
26-03-2019 12:28:43 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=81290, type_id=4, value='21111' where id=81293 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:08 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:08 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:08 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:08 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:29:08 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:09 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:09 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:09 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:09 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:29:09 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19262) already exists.
26-03-2019 12:29:12 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79264, type_id=4, value='19262' where id=79267 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 21662) already exists.
26-03-2019 12:29:16 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=2980949, type_id=4, value='21662' where id=2980952 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19772) already exists.
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19772) already exists.
26-03-2019 12:29:19 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=79611, type_id=4, value='19772' where id=79614 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:29:20 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 19861) already exists.
26-03-2019 12:29:50 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=123920, type_id=4, value='19861' where id=123922 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] WARN  ate.util.JDBCExceptionReporter - SQL Error: 0, SQLState: 23505
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] ERROR ate.util.JDBCExceptionReporter - ERROR: duplicate key value violates unique constraint "unique_identifier_type"
  Detail: Key (type_id, value)=(4, 20165) already exists.
26-03-2019 12:30:03 [SwingWorker-pool-3-thread-1] ERROR .AbstractFlushingEventListener - Could not synchronize database state with session
org.hibernate.exception.ConstraintViolationException: Could not execute JDBC batch update
	at org.hibernate.exception.SQLStateConverter.convert(SQLStateConverter.java:71)
	at org.hibernate.exception.JDBCExceptionHelper.convert(JDBCExceptionHelper.java:43)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:253)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:237)
	at org.hibernate.engine.ActionQueue.executeActions(ActionQueue.java:142)
	at org.hibernate.event.def.AbstractFlushingEventListener.performExecutions(AbstractFlushingEventListener.java:298)
	at org.hibernate.event.def.DefaultFlushEventListener.onFlush(DefaultFlushEventListener.java:27)
	at org.hibernate.impl.SessionImpl.flush(SessionImpl.java:1000)
	at org.hibernate.impl.SessionImpl.managedFlush(SessionImpl.java:338)
	at org.hibernate.transaction.JDBCTransaction.commit(JDBCTransaction.java:106)
	at org.ccs.openmrs.migracao.entidadesHibernate.ImportDao.PatientIdentifierImportDao.closeCurrentSessionwithTransaction(PatientIdentifierImportDao.java:42)
	at org.ccs.openmrs.migracao.entidadesHibernate.importPatient.PatientIdentifierImportService.update(PatientIdentifierImportService.java:30)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:139)
	at org.ccs.openmrs.migracao.swingreverse.Task1.doInBackground(Task1.java:56)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:296)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at javax.swing.SwingWorker.run(SwingWorker.java:335)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
Caused by: java.sql.BatchUpdateException: Batch entry 0 update PatientIdentifier set patient_id=104845, type_id=4, value='20165' where id=104848 was aborted.  Call getNextException to see the cause.
	at org.postgresql.jdbc2.AbstractJdbc2Statement$BatchResultHandler.handleError(AbstractJdbc2Statement.java:2743)
	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1928)
	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:405)
	at org.postgresql.jdbc2.AbstractJdbc2Statement.executeBatch(AbstractJdbc2Statement.java:2892)
	at org.hibernate.jdbc.BatchingBatcher.doExecuteBatch(BatchingBatcher.java:48)
	at org.hibernate.jdbc.AbstractBatcher.executeBatch(AbstractBatcher.java:246)
	... 17 more
